icon:
  host: ${ORDS_HOST}
  hsr-service-url: ${HSR_SERVICE_URL}
  pac-queue: ${PAC_QUEUE_NAME}
  hsr-queue: ${HSR_QUEUE_NAME}
  ping-queue: ${PING_QUEUE_NAME}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: 5672

server:
  port: 8081
