pac:
  ords:
    host: "http://127.0.0.1/"
    endpoints:
      poll: "events"
      success: "success"
      events:
        type: "events/type"
  pac-queue: ${PAC_QUEUE_NAME:pac-queue}
  pac-routing-key: ${PAC_ROUTING_KEY:PAC}
  exchange-name: ${RABBIT_EXCHANGE_NAME:EXCHANGE}


spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    port: 5672
    username: ${RABBIT_MQ_HOST}
    password: ${RABBIT_MQ_HOST}

server:
  port: ${POLLER_SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}