# Used to trigger deployment to test and prod Openshift environnment by Image stream re-tagging and labelling pod
name: Trigger deployment to test and prod Openshift environnment by Image stream re-tagging and labelling pod

on:
  workflow_dispatch:
    inputs:
      app1:
        description: 'App Name (jag-cmsint-pac-poller)'
        required: true
        default: 'jag-cmsint-pac-poller'
      app2:
        description: 'App Name (jag-cmsint-pac-consumer)'
        required: true
        default: 'jag-cmsint-pac-consumer'
      imageSourceEnv:
        description: 'Image Source Env'
        required: true
        default: 'dev'
      imageTargetEnv:
        description: 'Target Release Env'
        required: true
jobs:
  oc-image-tagging:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.imageTargetEnv }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # Get the version number which is prefixed with the Github release branches in format release/{version}
      - name: Get Release Version
        run: |
          branch=${GITHUB_REF##*/}
          version=$(echo $branch | cut -d "/" -f2-)
          echo "releaseVersion=$version" >> $GITHUB_ENV

      # Get Git latest short Sha# from the release branch used. This Sha# will be used in image tagging as well as DC Pod labelling.
      - name: Get git commit short sha
        id: sha
        run: |
          shortSha=$(echo $(git rev-parse --short HEAD) | cut -c1-7)
          echo "gitsha=$shortSha" >> $GITHUB_ENV

      # Prints vital release paramters used
      - name: Print Release Variables
        run: |
          echo "Release Application 1: ${{ github.event.inputs.app1 }}"
          echo "Release Application 2: ${{ github.event.inputs.app2 }}"
          echo "Release Environment: ${{ github.event.inputs.imageTargetEnv }}"
          echo "Release Version: ${{ env.releaseVersion }}"
          echo "Release Git Sha: ${{env.gitsha}}"

      #Login to Openshift using OC Tools SA and Token for image stream tagging changes - Kamloops (OC PROD)
      - name: Authenticate OC Tools SA - Kamloops (OC PROD)
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_TOOLS_DEPLOYER_NAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_SA_TOOLS_DEPLOYER_TOKEN}}
          namespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}

      # Re-Tag latest dev (source) jag-cmsint-pac-poller image to other env to trigger openshift deployment via DeploymentConfig
      # It also creates a tag with release version number to use it in case of rollback..
      - name: Retag jag-cmsint-pac-poller image to release env and version - Kamloops (OC PROD)
        env:
          appName: ${{ github.event.inputs.app1 }}
          imageSourceEnv: ${{ github.event.inputs.imageSourceEnv }}
          imageTargetEnv: ${{ github.event.inputs.imageTargetEnv }}
          openshiftToolsNamespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          openshiftIImageRegistry: ${{secrets.OPENSHIFT_INTERNAL_REPOSITORY}}
          releaseVersion: ${{ env.releaseVersion }}
          gitSha: ${{ env.gitsha }}
        run: |
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageSourceEnv} ${appName}:${imageTargetEnv}
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageTargetEnv} ${appName}:${releaseVersion}.${gitSha}

      # Re-Tag latest dev (source) jag-cmsint-pac-consumer image to other env to trigger openshift deployment via DeploymentConfig
      # It also creates a tag with release version number to use it in case of rollback..
      - name: Retag jag-cmsint-pac-consumer image to release env and version - Kamloops (OC PROD)
        env:
          appName: ${{ github.event.inputs.app2 }}
          imageSourceEnv: ${{ github.event.inputs.imageSourceEnv }}
          imageTargetEnv: ${{ github.event.inputs.imageTargetEnv }}
          openshiftToolsNamespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          openshiftIImageRegistry: ${{secrets.OPENSHIFT_INTERNAL_REPOSITORY}}
          releaseVersion: ${{ env.releaseVersion }}
          gitSha: ${{ env.gitsha }}
        run: |
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageSourceEnv} ${appName}:${imageTargetEnv}
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageTargetEnv} ${appName}:${releaseVersion}.${gitSha}

      #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Kamloops (OC PROD)
      - name: Authenticate OC Env Specific SA - Kamloops (OC PROD)
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN}}
          namespace: ${OPENSHIFT_NAMESPACE}

      # Labels the deployment config of the jag-cmsint-pac-poller application with release version number to spin up the pods labelled in same version - Kamloops (OC PROD)
      - name: Labelling jag-cmsint-pac-poller DC to release version - Kamloops (OC PROD)
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{ github.event.inputs.ap1 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'

      # Wait to jag-cmsint-pac-poller DC rollout to get completed before proceeding next stage - Kamloops (OC PROD)
      - name: Wait for jag-cmsint-pac-poller DC rollout - Kamloops (OC PROD)
        env:
          appName: ${{ github.event.inputs.app1 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # Labels the deployment config of the jag-cmsint-pac-consumer application with release version number to spin up the pods labelled in same version - Kamloops (OC PROD)
      - name: Labelling jag-cmsint-pac-consumer DC to release version - Kamloops (OC PROD)
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{ github.event.inputs.ap2 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'

      # Wait to jag-cmsint-pac-consumer DC rollout to get completed before proceeding next stage - Kamloops (OC PROD)
      - name: Wait for jag-cmsint-pac-consumer DC rollout - Kamloops (OC PROD)
        env:
          appName: ${{ github.event.inputs.app2 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      #Login to Openshift using OC Tools SA and Token for image stream tagging changes - Calgary (OC DR)
      - name: Authenticate OC Tools SA - Calgary (OC DR)
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_TOOLS_DEPLOYER_NAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_DR}}
          openshift_token: ${{secrets.OPENSHIFT_SA_TOOLS_DEPLOYER_TOKEN_DR}}
          namespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}

      # Re-Tag latest dev (source) jag-cmsint-pac-poller image to other env to trigger openshift deployment via DeploymentConfig
      # It also creates a tag with release version number to use it in case of rollback.
      - name: Retag jag-cmsint-pac-poller image to release env and version - Calgary (OC DR)
        env:
          appName: ${{ github.event.inputs.app1 }}
          imageSourceEnv: ${{ github.event.inputs.imageSourceEnv }}
          imageTargetEnv: ${{ github.event.inputs.imageTargetEnv }}
          openshiftToolsNamespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          openshiftIImageRegistry: ${{secrets.OPENSHIFT_INTERNAL_REPOSITORY}}
          releaseVersion: ${{ env.releaseVersion }}
          gitSha: ${{ env.gitsha }}
        run: |
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageSourceEnv} ${appName}:${imageTargetEnv}
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageTargetEnv} ${appName}:${releaseVersion}.${gitSha}

      # Re-Tag latest dev (source) jag-cmsint-pac-consumer image to other env to trigger openshift deployment via DeploymentConfig
      # It also creates a tag with release version number to use it in case of rollback.
      - name: Retag jag-cmsint-pac-consumer image to release env and version - Calgary (OC DR)
        env:
          appName: ${{ github.event.inputs.app2 }}
          imageSourceEnv: ${{ github.event.inputs.imageSourceEnv }}
          imageTargetEnv: ${{ github.event.inputs.imageTargetEnv }}
          openshiftToolsNamespace: ${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}
          openshiftIImageRegistry: ${{secrets.OPENSHIFT_INTERNAL_REPOSITORY}}
          releaseVersion: ${{ env.releaseVersion }}
          gitSha: ${{ env.gitsha }}
        run: |
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageSourceEnv} ${appName}:${imageTargetEnv}
          oc tag ${openshiftIImageRegistry}/${openshiftToolsNamespace}/${appName}:${imageTargetEnv} ${appName}:${releaseVersion}.${gitSha}

      #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Calgary (OC DR)
      - name: Authenticate OC Env Specific SA - Calgary (OC DR)
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_DR}}
          openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN_DR}}
          namespace: ${OPENSHIFT_NAMESPACE}

      # Labels the deployment config of the jag-cmsint-pac-poller application with release version number to spin up the pods labelled in same version - Calgary (OC DR)
      - name: Labelling jag-cmsint-pac-poller DC to release version - Calgary (OC DR)
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{ github.event.inputs.app1 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'


      # Wait to jag-cmsint-pac-poller DC rollout to get completed before proceeding next stage - Calgary (OC DR)
      - name: Wait for jag-cmsint-pac-poller DC rollout - Calgary (OC DR)
        env:
          appName: ${{ github.event.inputs.app1 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # Labels the deployment config of the jag-cmsint-pac-consumer application with release version number to spin up the pods labelled in same version - Calgary (OC DR)
      - name: Labelling jag-cmsint-pac-consumer DC to release version - Calgary (OC DR)
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{ github.event.inputs.app2 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'


      # Wait to jag-cmsint-pac-consumer DC rollout to get completed before proceeding next stage - Calgary (OC DR)
      - name: Wait for jag-cmsint-pac-consumer DC rollout - Calgary (OC DR)
        env:
          appName: ${{ github.event.inputs.app2 }}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch